# Generated by Django 5.0.4 on 2024-05-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shortenedurl_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
